# Generated by Django 4.0.2 on 2022-02-27 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('telegram_id', models.CharField(max_length=128, null=True)),
                ('telegram_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
